"""Secrets manager.

Handles encryption/decryption of environment variables and .env file management.
"""

import base64
import os
import re
from pathlib import Path

KEY_FILE = ".forge/key"


class SecretsManager:
    """Manages secrets encryption and .env files."""

    def __init__(self, base_path: Path | None = None):
        self.base = base_path or Path.cwd()
        self.key_path = self.base / KEY_FILE

    def _get_or_create_key(self, key: str | None = None) -> bytes:
        if key:
            return base64.b64decode(key.encode()) if len(key) > 32 else key.encode()
        if self.key_path.exists():
            return base64.b64decode(self.key_path.read_text(encoding="utf-8").strip())
        raw = os.urandom(32)
        self.key_path.parent.mkdir(parents=True, exist_ok=True)
        self.key_path.write_text(base64.b64encode(raw).decode(), encoding="utf-8")
        return raw

    def _xor_bytes(self, data: bytes, key: bytes) -> bytes:
        key_len = len(key)
        return bytes(b ^ key[i % key_len] for i, b in enumerate(data))

    def encrypt_env(self, env_dict: dict, key: str | None = None) -> dict:
        """Encrypt environment variables. Returns dict of encrypted values."""
        raw_key = self._get_or_create_key(key)
        encrypted = {}
        for k, v in env_dict.items():
            encoded = base64.b64encode(self._xor_bytes(v.encode(), raw_key)).decode()
            encrypted[k] = encoded
        return encrypted

    def decrypt_env(self, encrypted: dict, key: str | None = None) -> dict:
        """Decrypt environment variables."""
        raw_key = self._get_or_create_key(key)
        decrypted = {}
        for k, v in encrypted.items():
            decoded = base64.b64decode(v.encode())
            decrypted[k] = self._xor_bytes(decoded, raw_key).decode()
        return decrypted

    def generate_env_file(self, secrets: dict, output: str = ".env") -> str:
        """Generate .env file with placeholder secrets. Returns file path."""
        lines = ["# Generated by Forge — do not commit this file", ""]
        for k in secrets:
            placeholder = secrets[k] if secrets[k] else f"CHANGE_ME_{k}"
            lines.append(f"{k}={placeholder}")
        out_path = self.base / output
        out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        return str(out_path)

    def validate_env_file(self, path: str | None = None) -> list[dict]:
        """Validate .env file for common issues."""
        env_path = Path(path) if path else self.base / ".env"
        issues = []

        if not env_path.exists():
            issues.append({"line": 0, "issue": "File not found", "value": str(env_path)})
            return issues

        lines = env_path.read_text(encoding="utf-8").splitlines()
        seen_vars = {}

        for i, line in enumerate(lines, 1):
            stripped = line.strip()
            if not stripped or stripped.startswith("#"):
                continue

            if "=" not in stripped:
                issues.append({"line": i, "issue": "Missing '=' separator", "value": stripped})
                continue

            key, _, value = stripped.partition("=")
            key = key.strip()
            value = value.strip()

            if not key:
                issues.append({"line": i, "issue": "Empty variable name", "value": stripped})
                continue

            if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key):
                issues.append({"line": i, "issue": "Invalid variable name", "value": key})

            if key in seen_vars:
                issues.append({"line": i, "issue": f"Duplicate variable '{key}'", "value": value})
            seen_vars[key] = i

            if value.startswith('"') and value.endswith('"'):
                pass
            elif value.startswith("'") and value.endswith("'"):
                pass
            elif " " in value and value not in ("true", "false", "null", ""):
                issues.append({"line": i, "issue": "Unquoted value with spaces", "value": value})

            if value in ("", "CHANGE_ME", "changeme", "TODO"):
                issues.append({"line": i, "issue": "Placeholder/empty value", "value": value})

            if "password" in key.lower() or "secret" in key.lower() or "token" in key.lower():
                if value in ("password", "secret", "token", "changeme", ""):
                    issues.append({"line": i, "issue": "Weak/default secret value", "value": "***"})

        return issues

    def init_secrets(self) -> dict:
        """Initialize secrets management. Creates .forge/key if not exists."""
        self._get_or_create_key()
        return {"key_file": str(self.key_path), "status": "initialized"}
